### ISSUE TITLE
make_tsne.py loading model state dict error

### ISSUE THREAD

**Issue by devtrace404** [csiro-robotics/TCE#1]
`python make_tsne.py`
> Built model : resnet50
Loading checkpoint from checkpoint/ckpt_epoch_50.pth
Traceback (most recent call last):
  File "make_tsne.py", line 131, in <module>
    model = build_model(arg.model, arg.ckpt)
  File "make_tsne.py", line 56, in build_model
    model.load_state_dict(checkpoint)
  File "/home/cv/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
        Unexpected key(s) in state_dict: "fc_2.weight", "fc_2.bias", "bn_2.weight", "bn_2.bias", "bn_2.running_mean", "bn_2.running_var", "bn_2.num_batches_tracked", "fc_3.weight", "fc_3.bias", "bn_3.weight", "bn_3.bias", "bn_3.running_mean", "bn_3.running_var", "bn_3.num_batches_tracked", "fc_4.weight", "fc_4.bias". 

I downloaded the model weights for ResNet50 pre-trained on Kinetics400 dataset from this [url](https://cloudstor.aarnet.edu.au/plus/s/HpPIzGgB9e950xJ).

**Comment by JBKnights** [comment]
Hello!  We've majorly updated this repository - please use the new instructions, training script and checkpoint to generate the tsne.  Cheers, and please log a new issue if you find any further difficulties!
